### ISSUE TITLE
Generated ETags are not RFC 7232 compliant

### ISSUE THREAD

**Issue by epifab** [daviddenton/fintrospect#46]
According to the RFC 7232, ETags should be wrapped in double quotes.
ETags generated by fintrospect cause the following warnings to be raised by our Akka http client:
`Illegal header: Illegal 'etag' header: Invalid input 'd', expected 'W' or opaque-tag (line 1, column 1): d41d8cd98f00b204e9800998ecf8427e`

**Comment by daviddenton** [comment]
Hi @epifab  - if you'd like to expediate the timing of a fix and would like to contribute a fix via PR, it should be trivial. It's only a small fix in Caching.scala.

:)

**Comment by daviddenton** [comment]
Fixed this in 14.21.2

**Comment by epifab** [comment]
ah, that was quick! thanks @daviddenton
